#!/usr/bin/env bash
#
# export-mariadb-grants.sh
#
# Purpose:
#   Export MariaDB users + grants in a restore-friendly SQL format (CREATE USER + GRANT ...)
#   suitable as an "instance metadata" artifact for backups and disaster recovery.
#
# Recommended usage:
#   - Run inside the MariaDB container (no SSH required if invoked via `incus exec`)
#   - Store output on persistent storage (e.g., /var/lib/mysql or a dedicated backup dir)
#
# Example (from host):
#   incus exec mariadb -- /usr/local/sbin/export-mariadb-grants.sh
#
set -euo pipefail

# ---- Configuration ----------------------------------------------------------

# Where to write the resulting SQL file.
# Put it on persistent storage that BackupPC will collect.
OUT="/var/lib/mysql/grants.sql"

# User and group to own the resulting SQL file.
OUT_USER="mysql"
OUT_GROUP="mysql"

# Optional: restrict output file permissions (defense-in-depth).
OUT_MODE="0600"

# Optional: include a statement to disable binlogging during import (harmless on non-replica).
# Keeping this enabled is useful if you ever import on a replica and do NOT want grants to replicate.
DISABLE_BINLOG_ON_IMPORT="yes"

# Optional: if you want to skip "system-ish" accounts, define a regex here.
# Leave empty to export everything from mysql.user.
# Examples:
#   SKIP_USER_REGEX='^(mysql|mariadb\.sys)$'
SKIP_USER_REGEX=""

# ---- Helpers ----------------------------------------------------------------

log() {
  printf '[%s] %s\n' "$(date -Iseconds)" "$*" >&2
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    log "ERROR: required command not found: $1"
    exit 1
  }
}

# ---- Preconditions -----------------------------------------------------------

require_cmd mariadb
require_cmd mktemp
require_cmd chmod
require_cmd date

# Ensure output directory exists
OUT_DIR="$(dirname "$OUT")"
if [[ ! -d "$OUT_DIR" ]]; then
  log "ERROR: output directory does not exist: $OUT_DIR"
  exit 1
fi

# Create temp file for the account list
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# ---- Collect accounts --------------------------------------------------------

log "Collecting accounts from mysql.user ..."

# This returns rows like:  'user'@'host'  (already properly quoted for SQL)
mariadb -N -e "
  SELECT CONCAT(QUOTE(User), '@', QUOTE(Host))
  FROM mysql.user
  ORDER BY User, Host
" > "$TMP"

if [[ -s "$TMP" ]]; then
  log "Found $(wc -l < "$TMP") account(s)"
else
  log "ERROR: no accounts found (unexpected)."
  exit 1
fi

# ---- Generate grants.sql -----------------------------------------------------

log "Writing grants export to: $OUT"

{
  echo "-- grants export $(date -Iseconds)"
  echo "-- generated by: $(basename "$0")"
  echo

  # Optional: keep privilege import from affecting replication/binlogs
  if [[ "$DISABLE_BINLOG_ON_IMPORT" == "yes" ]]; then
    echo "SET sql_log_bin = 0;"
    echo
  fi

  # Emit one block per account
  while read -r acct; do
    # acct is like:  'someuser'@'somehost'
    # Derive username (without quotes) for skip filtering if requested.
    if [[ -n "$SKIP_USER_REGEX" ]]; then
      # Extract the left side of 'user'@'host' and strip leading/trailing quotes.
      user="${acct%%@*}"
      user="${user#\'}"
      user="${user%\'}"
      if [[ "$user" =~ $SKIP_USER_REGEX ]]; then
        echo "-- skipped: $acct"
        echo
        continue
      fi
    fi

    echo "-- $acct"

    # CREATE USER statement (MariaDB may not support SHOW CREATE USER for some internal/system entries;
    # we tolerate failures and still try SHOW GRANTS).
    mariadb -N -e "SHOW CREATE USER $acct;" 2>/dev/null || true

    # GRANT statements
    mariadb -N -e "SHOW GRANTS FOR $acct;" 2>/dev/null || true

    echo
  done < "$TMP"

} > "$OUT"

chmod "$OUT_MODE" "$OUT"
chown "$OUT_USER:$OUT_GROUP" "$OUT"

log "Done. File permissions set to $OUT_MODE"
log "Tip: include $OUT in your backup/BackupPC set."

